(function(){
const COOKIE="atcx_preferences";
const CONSENT="atcx_cookie_consent";
const DAY=60*60*24*365;

const PREFS="atcx_preferences_local";

function readCookie(){
  let local={};
  try{local=JSON.parse(localStorage.getItem(PREFS)||"{}")||{}}catch(e){}
  const m=document.cookie.match(new RegExp("(?:^|; )"+COOKIE.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"=([^;]*)"));
  if(!m)return local;
  try{return Object.assign(local,JSON.parse(decodeURIComponent(m[1]))||{})}catch(e){return local}
}
function saveCookie(v){
  const data={lang:v.lang||"vi",theme:v.theme||"dark",bg:v.bg||""};
  try{localStorage.setItem(PREFS,JSON.stringify(data))}catch(e){}
  if(hasConsent())document.cookie=COOKIE+"="+encodeURIComponent(JSON.stringify(data))+"; Max-Age="+DAY+"; Path=/; SameSite=Lax";
}
function delCookie(){
  try{localStorage.removeItem(PREFS)}catch(e){}
  document.cookie=COOKIE+"=; Max-Age=0; Path=/; SameSite=Lax";
}
function hasConsent(){return localStorage.getItem(CONSENT)==="yes"}
function setConsent(v){localStorage.setItem(CONSENT,v?"yes":"no")}

const tr={
"⚙️ ATCX Settings":"⚙️ ATCX Settings",
"Điều khiển toàn bộ thông số của phòng thí nghiệm.":"Control all laboratory parameters.",
"← Phòng thí nghiệm":"← Laboratory",
"Áp dụng":"Apply",
"🎨 Giao diện":"🎨 Interface",
"Khôi phục mặc định":"Restore Defaults",
"🎨 Giao diện nhanh":"🎨 Quick Interface",
"×":"×",
"Ngôn ngữ":"Language",
"🇻🇳 Tiếng Việt":"🇻🇳 Vietnamese",
"🇬🇧 English":"🇬🇧 English",
"Chủ đề":"Theme",
"🌙 Tối":"🌙 Dark",
"☀️ Sáng":"☀️ Light",
"Ảnh nền URL":"Background URL",
"Hoặc chọn ảnh từ máy":"Or choose an image from your computer",
"Không ảnh nền":"No background",
"Phòng thí nghiệm":"Laboratory",
"Không gian":"Space",
"Cookie: —":"Cookie: —",
"🗑️ Xóa cookie":"🗑️ Delete cookie",
"Xem trước":"Preview",
"Lưu giao diện":"Save Interface",
"🍪 Dữ liệu cookie":"🍪 Cookie Data",
"Chỉ lưu ngôn ngữ, chủ đề sáng/tối và ảnh nền. Không lưu thông số mô phỏng bằng cookie.":"Only the language, light/dark theme, and background are stored. Simulation parameters are not stored in cookies.",
"🗑️ Xóa dữ liệu cookie":"🗑️ Delete cookie data",
"🍪 Hỏi lại về cookie":"🍪 Ask about cookies again",
"Khối lượng":"Mass",
"Kích thước":"Dimensions",
"Động lực học":"Dynamics",
"Mòn & vật liệu":"Wear & Materials",
"Môi trường":"Environment",
"Kích thích & lực":"Excitation & Forces",
"Camera & hiển thị":"Camera & Display",
"Thông số khác":"Other Parameters",
"Zoom":"Zoom",
"Camera X":"Camera X",
"Camera Y":"Camera Y",
"Lưới tọa độ chuẩn":"Standard coordinate grid",
"Vector vận tốc và gió":"Velocity and wind vectors",
"Nhãn vật lý các điểm khối lượng":"Physical labels for mass points",
"m₁ — vật 1":"m₁ — mass 1",
"m₂ — vật 2":"m₂ — mass 2",
"M₁ thanh — thanh 1":"M₁ rod — rod 1",
"M₂ thanh — thanh 2":"M₂ rod — rod 2",
"m₁ giữa — điểm giữa thanh 1":"m₁ midpoint — rod 1",
"m₂ giữa — điểm giữa thanh 2":"m₂ midpoint — rod 2",
"m₁ đầu — khối tập trung đầu thanh 1":"m₁ end — rod 1 end mass",
"m₂ đầu — khối tập trung đầu thanh 2":"m₂ end — rod 2 end mass",
"⚖️ Điều khiển khối lượng nâng cao":"⚖️ Advanced Mass Control",
"Tổng khối lượng 5 vị trí":"Total mass for 5 positions",
"Vị trí 1 — m₁":"Position 1 — m₁",
"Vị trí 2 — m₂":"Position 2 — m₂",
"Vị trí 3 — giữa thanh 1":"Position 3 — rod 1 midpoint",
"Vị trí 4 — giữa thanh 2":"Position 4 — rod 2 midpoint",
"Vị trí 5 — đầu thanh 1":"Position 5 — rod 1 end",
"⚖️ Chia đều tổng khối lượng cho 5 vị trí":"⚖️ Distribute total mass across 5 positions",
"✅ Áp dụng 5 giá trị vào mô hình":"✅ Apply 5 values to the model",
"Hình học & Cấu trúc":"Geometry & Structure",
"Điều kiện ban đầu":"Initial Conditions",
"Gia tốc trọng trường g":"Gravitational acceleration g",
"Trái Đất":"Earth",
"Mặt Trăng":"Moon",
"Sao Hỏa":"Mars",
"Mộc Tinh":"Jupiter",
"Không trọng lực":"Zero gravity",
"Vật liệu & Hao mòn ổ khớp":"Materials & Joint Wear",
"Chất liệu cấu tạo (Chịu lực ly tâm)":"Material (Centrifugal Resistance)",
"s1 - Vật liệu gốc (Tiêu chuẩn)":"s1 - Base Material (Standard)",
"s2 - Thép (Cứng, chịu ly tâm tốt)":"s2 - Steel (Hard, high centrifugal resistance)",
"s3 - Titanium (Rất cứng, siêu bền)":"s3 - Titanium (Very hard, ultra durable)",
"s4 - Sắt (Cứng trung bình)":"s4 - Iron (Medium hardness)",
"s5 - Dây thừng (Mềm, mòn/đứt nhanh)":"s5 - Rope (Soft, wears/breaks quickly)",
"Nhớt b₁":"Damping b₁",
"Nhớt b₂":"Damping b₂",
"Ma sát khô τ₁":"Dry friction τ₁",
"Ma sát khô τ₂":"Dry friction τ₂",
"Hệ số mòn cơ bản":"Base wear rate",
"🔬 Chế độ nghiên cứu":"🔬 Research Mode",
"Tốc độ mòn":"Wear speed",
"x1 Chuẩn":"x1 Normal",
"x5 Nhanh":"x5 Fast",
"x10 Tối đa":"x10 Maximum",
"Giới hạn giảm năng lượng":"Energy reduction limit",
"🚀 Tối ưu hiệu năng CPU/GPU":"🚀 CPU/GPU Performance Optimization",
"Đang phát hiện CPU/GPU...":"Detecting CPU/GPU...",
"Mức giảm năng lượng mỗi giây":"Energy reduction per second",
"Không khí & Gió động":"Air & Dynamic Wind",
"Nhiệt độ":"Temperature",
"Áp suất":"Pressure",
"Gió tĩnh":"Static wind",
"Hướng gió":"Wind direction",
"Gió giật":"Wind gust",
"Chu kỳ giật":"Gust period",
"Cd vật":"Mass Cd",
"Cd thanh":"Rod Cd",
"Cản không khí":"Air resistance",
"Bật gió":"Enable wind",
"Độ nhớt μ":"Viscosity μ",
"Mật độ chất lưu ρf":"Fluid density ρf",
"Lực đẩy Archimedes":"Buoyant force",
"Môi trường nâng cao & Rung":"Advanced Environment & Vibration",
"Hệ số ρ khí":"Air density factor",
"Hệ số nhớt môi trường":"Environment viscosity factor",
"Biên độ rung":"Vibration amplitude",
"Tần số rung":"Vibration frequency",
"Hướng rung":"Vibration direction",
"Lực ngoại vi (Ném/Đẩy)":"External Force (Throw/Push)",
"Lực F":"Force F",
"Hướng lực":"Force direction",
"Thời gian":"Duration",
"Tác dụng lên m₁":"Apply to m₁",
"Tác dụng lên m₂":"Apply to m₂",
"Tác dụng lực":"Force target",
"ĐIỀU KHIỂN MÔ PHỎNG":"SIMULATION CONTROL",
"Tốc độ thời gian":"Time speed",
"Vệt quỹ đạo":"Trajectory trail",
"Âm thanh mô phỏng":"Simulation sound",
"Độ mòn vô hạn — không đứt dây":"Infinite wear — rope never breaks",
"Tính cản không khí":"Air resistance",
"Lực nổi":"Buoyancy",
"Bật giảm năng lượng J/s":"Enable energy reduction J/s",
"Chế độ hiệu năng":"Performance mode",
"targetLock":"Target lock",
"gridOn":"Coordinate grid",
"vectors":"Velocity/wind vectors",
"labels":"Physical labels",
"Lựa chọn hệ thống":"System Selection",
"Tự thiết lập":"Auto setup",
"Chọn mục tiêu":"Choose target",
"m₁":"m₁",
"m₂":"m₂",
"Giữa thanh 1":"Rod 1 midpoint",
"Giữa thanh 2":"Rod 2 midpoint",
"Đầu thanh 1":"Rod 1 end",
"Đầu thanh 2":"Rod 2 end",
"Tác dụng lên m₁":"Apply to m₁",
"Tác dụng lên m₂":"Apply to m₂",
"Đã lưu Settings":"Settings saved",
"Khôi phục toàn bộ giá trị mặc định?":"Restore all default values?",
"Bạn chưa chấp nhận cookie":"You have not accepted cookies",
"Đã lưu giao diện":"Interface saved",
"Đã lưu giao diện vào cookie":"Interface saved to cookies",
"Đã xóa cookie giao diện":"Interface cookies deleted",
"Đã xóa dữ liệu cookie":"Cookie data deleted",
"Đã đặt lại yêu cầu đồng ý":"Cookie consent request reset",
"Đã chấp nhận":"Accepted",
"Chưa chấp nhận":"Not accepted",
"Cookie: ":"Cookie: ",
"Cookie: Đã chấp nhận":"Cookie: Accepted",
"Cookie: Chưa chấp nhận":"Cookie: Not accepted",
"Cookie: Đã xóa":"Cookie: Deleted",
"🍪 Dữ liệu cookie":"🍪 Cookie Data",
"Web chỉ dùng cookie để lưu ":"The website only uses cookies to store ",
"ngôn ngữ, giao diện sáng/tối và ảnh nền":"language, light/dark interface, and background",
". Bạn có thể xóa dữ liệu này bất cứ lúc nào trong Settings.":". You can delete this data at any time in Settings.",
"Không chấp nhận":"Decline",
"Chấp nhận":"Accept",
"Xem thêm →":"Learn more →"
};

Object.assign(tr,{"Con lắc kép": "Double Pendulum", "Phòng thí nghiệm động lực học — mô hình cơ học Lagrange + RK4": "Dynamics laboratory — Lagrangian mechanics model + RK4", "🧪 Mô hình vật lý:": "🧪 Physical model:", "⚙️ Mở bảng Settings": "⚙️ Open Settings", "Âm thanh & Tính năng thực tế": "Sound & Real-time Features", "Âm thanh mô phỏng (Gió & Khớp ma sát)": "Simulation sound (Wind & friction joints)", "Chế độ độ mòn vô hạn (Không đứt, bỏ qua 100%)": "Infinite wear mode (Never breaks, ignore 100%)", "Camera & Quan sát": "Camera & Observation", "Kéo trực tiếp m₁, m₂ để đổi vị trí/ném. Kéo nền để xoay góc nhìn. Cuộn chuột để zoom.": "Drag m₁ and m₂ directly to move/throw them. Drag the background to rotate the view. Scroll to zoom.", "8 thông số khối lượng — chỉnh chính xác": "8 mass parameters — precise adjustment", "Theo dõi mục tiêu": "Target Tracking", "Chế độ": "Mode", "Mục tiêu": "Target", "Thiết lập mục tiêu": "Set target", "Khóa mục tiêu": "Lock target", "Chưa thiết lập mục tiêu": "Target not configured", "Di chuột lên mô hình": "Hover over the model", "Đưa chuột tới m₁, m₂ hoặc giữa thanh để xem chi tiết.": "Move the mouse to m₁, m₂, or a rod midpoint to view details.", "Thu gọn": "Collapse", "Mở rộng": "Expand", "Gốc": "Base material", "Thép": "Steel", "Sắt": "Iron", "Dây thừng": "Rope", "⚠️ HỆ THỐNG ĐÃ ĐỨT GÃY DO QUÁ TẢI LY TÂM!": "⚠️ SYSTEM FAILED DUE TO CENTRIFUGAL OVERLOAD!", "Hãy nhấn nút 'Reset hệ thống' để cài đặt lại.": "Press the 'Reset system' button to reset it.", "Đã ngắt mô phỏng": "Simulation disconnected", "Dừng": "Stop", "Tạm dừng": "Pause", "Tiếp tục": "Resume", "🟢 Gần dừng — động năng rất thấp": "🟢 Nearly stopped — very low kinetic energy", "🟡 Dao động yếu — sắp dừng": "🟡 Weak oscillation — nearly stopped", "🔵 Đang chuyển động mạnh": "🔵 Strong motion", "⚡ Đang dao động ổn định": "⚡ Stable oscillation", "Không xác định": "Unknown", "Đã dừng": "Stopped", " phút": " minutes", "Rất lâu / gần lý tưởng": "Very long / nearly ideal", "Nhập giá trị chính xác": "Enter an exact value", "GPU/WebGL khả dụng": "GPU/WebGL available", "luồng": "threads", "bật": "enabled", "tắt": "disabled", "Giữa thanh 1": "Rod 1 midpoint", "Giữa thanh 2": "Rod 2 midpoint", "Đầu thanh 1": "Rod 1 end", "Đầu thanh 2": "Rod 2 end", "Nhận diện rê chuột": "Hover detection", "Đưa chuột tới vật thể để nhận diện; thông tin này không cần khóa mục tiêu.": "Move the mouse over an object to detect it; target locking is not required.", "Phân rã động năng — kiểm tra chi tiết": "Kinetic energy decomposition — detailed check", "Phân rã thế năng": "Potential energy decomposition", "Trạng thái Cơ học": "Mechanical State", "Năng lượng còn lại": "Remaining energy", "Ngân sách năng lượng": "Energy budget", "Tỷ lệ còn lại": "Remaining ratio", "Biến thiên E": "E change", "Tốc độ hao hụt": "Dissipation rate", "Ước tính còn dao động": "Estimated remaining oscillation", "Mức chuyển động": "Motion level", "Chuyển hóa năng lượng": "Energy conversion", "bước": "step", "targetMode": "Target mode", "targetSelect": "Target selection", "material": "Material", "forceBody": "Force target", "M₁ thanh — thanh 1": "M₁ rod — rod 1", "M₂ thanh — thanh 2": "M₂ rod — rod 2", "Cd thanh": "Rod Cd", "Người thực hiện": "Created by", "Thu gọn/Mở rộng Bảng điều khiển": "Collapse/Expand control panel"});

Object.assign(tr,{
"Con lắc kép — Phòng thí nghiệm động lực học nâng cao":"Double Pendulum — Advanced Dynamics Laboratory",
"Thu gọn/Mở rộng Bảng điều khiển":"Collapse/Expand Control Panel",
"Chế độ":"Mode",
"Mục tiêu":"Target",
"Thiết lập mục tiêu":"Set Target",
"Khóa mục tiêu":"Lock Target",
"Chưa thiết lập mục tiêu":"Target not configured",
"👁️ Nhận diện rê chuột hoạt động độc lập: đưa chuột lên vật thể để xem thông tin thực tế, không cần khóa mục tiêu.":"👁️ Hover detection works independently: move the pointer over an object to inspect its live information; target locking is not required.",
"Di chuột lên mô hình":"Hover over the model",
"Đưa chuột tới m₁, m₂ hoặc giữa thanh để xem chi tiết.":"Move the pointer to m₁, m₂, or a rod midpoint to view details.",
"⚙️ Thiết lập mục tiêu":"⚙️ Set Target",
"Con lắc kép":"Double Pendulum",
"Phòng thí nghiệm động lực học — mô hình cơ học Lagrange + RK4":"Dynamics laboratory — Lagrangian mechanics model + RK4",
"2 khâu cứng, khối điểm + thanh đồng chất, động lực học Lagrange, tích phân RK4, trọng lực, cản khí động theo vận tốc tương đối, ma sát nhớt/Coulomb, lực nổi và giá đỡ rung. Năng lượng được tính từ trạng thái tức thời.":"Two rigid links, point masses and uniform rods, Lagrangian dynamics, RK4 integration, gravity, aerodynamic drag based on relative velocity, viscous/Coulomb friction, buoyancy, and vibrating support. Energy is calculated from the instantaneous state.",
"🧪 Mô hình vật lý:":"🧪 Physical model:",
"⚙️ Mở bảng Settings":"⚙️ Open Settings",
"Âm thanh & Tính năng thực tế":"Sound & Real-time Features",
"Âm thanh mô phỏng (Gió & Khớp ma sát)":"Simulation sound (Wind & friction joints)",
"Chế độ độ mòn vô hạn (Không đứt, bỏ qua 100%)":"Infinite wear mode (Never breaks, ignore 100%)",
"Camera & Quan sát":"Camera & Observation",
"Kéo trực tiếp m₁, m₂ để đổi vị trí/ném. Kéo nền để xoay góc nhìn. Cuộn chuột để zoom.":"Drag m₁ and m₂ directly to move or throw them. Drag the background to rotate the view. Scroll to zoom.",
"Lưới tọa độ chuẩn":"Standard coordinate grid",
"Vector vận tốc và gió":"Velocity and wind vectors",
"Nhãn vật lý các điểm khối lượng":"Physical labels for mass points",
"8 thông số khối lượng — chỉnh chính xác":"8 mass parameters — precise adjustment",
"Ví dụ: nhập ":"Example: enter ",
" rồi bấm “Chia đều” → mỗi vị trí ":" then click “Distribute” → each position ",
". Mỗi vị trí đều có thanh kéo riêng để chỉnh chính xác từng giá trị.":". Each position has its own slider for precise adjustment.",
"Hình học & Cấu trúc":"Geometry & Structure",
"Có thể chỉnh riêng chiều dài thanh 1 và thanh 2 để khảo sát ảnh hưởng của hình học đến chuyển động.":"You can adjust rod 1 and rod 2 lengths independently to study the effect of geometry on motion.",
"Điều kiện ban đầu":"Initial Conditions",
"Gia tốc trọng trường g":"Gravitational acceleration g",
"Trái Đất":"Earth",
"Mặt Trăng":"Moon",
"Sao Hỏa":"Mars",
"Mộc Tinh":"Jupiter",
"Không trọng lực":"Zero gravity",
"Vật liệu & Hao mòn ổ khớp":"Materials & Joint Wear",
"Chất liệu cấu tạo (Chịu lực ly tâm)":"Material (Centrifugal Resistance)",
"Giới hạn đứt được ước tính từ ứng suất kéo cực hạn của vật liệu và tiết diện tròn của thanh/dây. Đây là mô hình giáo dục; giá trị thực tế còn phụ thuộc hình dạng, khuyết tật, mối nối và hệ số an toàn.":"The failure limit is estimated from the material's ultimate tensile stress and the circular cross-section of the rod/rope. This is an educational model; real values also depend on geometry, defects, joints, and safety factors.",
"🔬 Chế độ nghiên cứu":"🔬 Research Mode",
"x1 Chuẩn":"x1 Normal",
"x5 Nhanh":"x5 Fast",
"x10 Tối đa":"x10 Maximum",
"🚀 Tối ưu hiệu năng CPU/GPU":"🚀 CPU/GPU Performance Optimization",
"Đang phát hiện CPU/GPU...":"Detecting CPU/GPU...",
"Không khí & Gió động":"Air & Dynamic Wind",
"Nhiệt độ":"Temperature",
"Áp suất":"Pressure",
"Gió tĩnh":"Static wind",
"Hướng gió":"Wind direction",
"Gió giật":"Wind gust",
"Chu kỳ giật":"Gust period",
"Cd vật":"Mass Cd",
"Cd thanh":"Rod Cd",
"Cản không khí":"Air resistance",
"Bật gió":"Enable wind",
"Độ nhớt μ":"Viscosity μ",
"Mật độ chất lưu ρf":"Fluid density ρf",
"Lực đẩy Archimedes":"Archimedes buoyancy",
"Môi trường nâng cao & Rung":"Advanced Environment & Vibration",
"Hệ số ρ khí":"Air density factor",
"Hệ số nhớt môi trường":"Environment viscosity factor",
"Biên độ rung":"Vibration amplitude",
"Tần số rung":"Vibration frequency",
"Hướng rung":"Vibration direction",
"Lực ngoại vi (Ném/Đẩy)":"External Force (Throw/Push)",
"Lực F":"Force F",
"Hướng lực":"Force direction",
"Thời gian":"Duration",
"Tác dụng lên m₁":"Apply to m₁",
"Tác dụng lên m₂":"Apply to m₂",
"Tác dụng lực":"Force target",
"ĐIỀU KHIỂN MÔ PHỎNG":"SIMULATION CONTROL",
"Tốc độ thời gian":"Time speed",
"Vệt quỹ đạo":"Trajectory trail",
"Âm thanh mô phỏng":"Simulation sound",
"Độ mòn vô hạn — không đứt dây":"Infinite wear — rope never breaks",
"Tính cản không khí":"Air resistance",
"Lực nổi":"Buoyancy",
"Bật giảm năng lượng J/s":"Enable energy reduction J/s",
"Chế độ hiệu năng":"Performance mode",
"Lựa chọn hệ thống":"System Selection",
"Tự thiết lập":"Auto setup",
"Chọn mục tiêu":"Choose target",
"Khối lượng":"Mass",
"Kích thước":"Dimensions",
"Động lực học":"Dynamics",
"Mòn & vật liệu":"Wear & Materials",
"Môi trường":"Environment",
"Kích thích & lực":"Excitation & Forces",
"Camera & hiển thị":"Camera & Display",
"Thông số khác":"Other Parameters",
"Chế độ & công tắc":"Modes & Switches",
"s1 - Vật liệu gốc (Tiêu chuẩn)":"s1 - Base Material (Standard)",
"s2 - Thép (Cứng, chịu ly tâm tốt)":"s2 - Steel (Hard, high centrifugal resistance)",
"s3 - Titanium (Rất cứng, siêu bền)":"s3 - Titanium (Very hard, ultra durable)",
"s4 - Sắt (Cứng trung bình)":"s4 - Iron (Medium hardness)",
"s5 - Dây thừng (Mềm, mòn/đứt nhanh)":"s5 - Rope (Soft, wears/breaks quickly)",
"m₁ — vật 1":"m₁ — mass 1",
"m₂ — vật 2":"m₂ — mass 2",
"M₁ thanh — thanh 1":"M₁ rod — rod 1",
"M₂ thanh — thanh 2":"M₂ rod — rod 2",
"m₁ giữa — điểm giữa thanh 1":"m₁ midpoint — rod 1 midpoint",
"m₂ giữa — điểm giữa thanh 2":"m₂ midpoint — rod 2 midpoint",
"m₁ đầu — khối tập trung đầu thanh 1":"m₁ end — rod 1 end mass",
"m₂ đầu — khối tập trung đầu thanh 2":"m₂ end — rod 2 end mass",
"⚖️ Điều khiển khối lượng nâng cao":"⚖️ Advanced Mass Control",
"Tổng khối lượng 5 vị trí":"Total mass for 5 positions",
"Vị trí 1 — m₁":"Position 1 — m₁",
"Vị trí 2 — m₂":"Position 2 — m₂",
"Vị trí 3 — giữa thanh 1":"Position 3 — rod 1 midpoint",
"Vị trí 4 — giữa thanh 2":"Position 4 — rod 2 midpoint",
"Vị trí 5 — đầu thanh 1":"Position 5 — rod 1 end",
"⚖️ Chia đều tổng khối lượng cho 5 vị trí":"⚖️ Distribute total mass across 5 positions",
"✅ Áp dụng 5 giá trị vào mô hình":"✅ Apply 5 values to the model",
"Độ dài thanh 1 — L₁":"Rod 1 length — L₁",
"Độ dài thanh 2 — L₂":"Rod 2 length — L₂",
"Đường kính thanh d₁":"Rod diameter d₁",
"Đường kính thanh d₂":"Rod diameter d₂",
"Bán kính vật r₁":"Mass radius r₁",
"Bán kính vật r₂":"Mass radius r₂",
"Nhớt b₁":"Damping b₁",
"Nhớt b₂":"Damping b₂",
"Ma sát khô τ₁":"Dry friction τ₁",
"Ma sát khô τ₂":"Dry friction τ₂",
"Hệ số mòn cơ bản":"Base wear rate",
"Tốc độ mòn":"Wear speed",
"Giới hạn giảm năng lượng":"Energy reduction limit",
"Đã lưu Settings":"Settings saved",
"Khôi phục toàn bộ giá trị mặc định?":"Restore all default values?",
"Bạn chưa chấp nhận cookie":"You have not accepted cookies",
"Đã lưu giao diện":"Interface saved",
"Đã lưu giao diện vào cookie":"Interface saved to cookies",
"Đã xóa cookie giao diện":"Interface cookies deleted",
"Đã xóa dữ liệu cookie":"Cookie data deleted",
"Đã đặt lại yêu cầu đồng ý":"Cookie consent request reset",
"Đã chấp nhận cookie":"Cookies accepted",
"Chưa chấp nhận cookie":"Cookies not accepted",
"Cookie: Đã chấp nhận":"Cookie: Accepted",
"Cookie: Chưa chấp nhận":"Cookie: Not accepted",
"Cookie: Đã xóa":"Cookie: Deleted",
"Không chấp nhận":"Decline",
"Chấp nhận":"Accept",
"Xem thêm →":"Learn more →",
"Hệ đang trao đổi liên tục giữa động năng và thế năng.":"The system is continuously exchanging kinetic and potential energy.",
"ℹ️ Năng lượng đang được theo dõi theo thời gian thực.":"ℹ️ Energy is being tracked in real time.",
"Dao động rõ":"Clear oscillation",
"⛔ Hệ thống đã dừng do quá tải":"⛔ System stopped due to overload",
"Mô phỏng đã chuyển sang trạng thái an toàn. Chuyển động của khối không còn được tính như con lắc liên kết.":"The simulation has entered a safe state. The mass is no longer calculated as a linked pendulum.",
"🛑 Cảnh báo: hệ đã vượt giới hạn cơ học. Hãy giảm lực, khối lượng, tốc độ hoặc tăng độ bền/giảm tác động.":"🛑 Warning: the system exceeded its mechanical limit. Reduce force, mass, or speed, or increase strength/reduce loading.",
"🟢 Gần dừng — động năng rất thấp":"🟢 Nearly stopped — very low kinetic energy",
"🟡 Dao động yếu — sắp dừng":"🟡 Weak oscillation — nearly stopped",
"🔵 Đang chuyển động mạnh":"🔵 Strong motion",
"⚡ Đang dao động ổn định":"⚡ Stable oscillation",
"Vận tốc góc và vận tốc của các khối đang rất nhỏ; phần lớn năng lượng động đã chuyển sang thế năng hoặc đã bị tiêu tán.":"Angular and linear velocities are very small; most kinetic energy has been converted to potential energy or dissipated.",
"🟢 Hệ sắp dừng. Nếu ma sát/cản vẫn khác 0, biên độ sẽ tiếp tục giảm.":"🟢 The system is nearing rest. If friction/drag remains nonzero, the amplitude will continue to decrease.",
"K → U + hao hụt":"K → U + dissipation",
"Rất yếu":"Very weak",
"Yếu":"Weak",
"Mạnh":"Strong",
"K ↔ U, biên độ giảm":"K ↔ U, decreasing amplitude",
"K trội → chuyển sang U":"K dominant → converting to U",
"Không xác định":"Unknown",
"Rất lâu / gần lý tưởng":"Very long / nearly ideal",
"Đã dừng":"Stopped",
"Dừng":"Stop",
"Tạm dừng":"Pause",
"Tiếp tục":"Resume",
" phút":" minutes",
"bước":"step",
"luồng":"threads",
"bật":"enabled",
"tắt":"disabled",
"Nhập giá trị chính xác":"Enter an exact value",
"GPU/WebGL khả dụng":"GPU/WebGL available",
"BẬT":"ON",
"TẮT":"OFF",
"Nhận diện rê chuột":"Hover detection",
"Đưa chuột tới vật thể để nhận diện; thông tin này không cần khóa mục tiêu.":"Move the pointer over an object to detect it; target locking is not required.",
"Phân rã động năng — kiểm tra chi tiết":"Kinetic energy decomposition — detailed check",
"Phân rã thế năng":"Potential energy decomposition",
"Trạng thái Cơ học":"Mechanical State",
"Năng lượng còn lại":"Remaining energy",
"Ngân sách năng lượng":"Energy budget",
"Tỷ lệ còn lại":"Remaining ratio",
"Biến thiên E":"E change",
"Tốc độ hao hụt":"Dissipation rate",
"Ước tính còn dao động":"Estimated remaining oscillation",
"Mức chuyển động":"Motion level",
"Chuyển hóa năng lượng":"Energy conversion"
,
"Reset hệ thống":"Reset system",
"BẢNG ĐO LƯỜNG NĂNG LƯỢNG":"ENERGY MEASUREMENT PANEL",
"Động năng (K)":"Kinetic energy (K)",
"Thế năng (|U|)":"Potential energy (|U|)",
"Tiêu hao (Loss)":"Dissipation (Loss)",
"Cơ năng hiện có (E)":"Current mechanical energy (E)",
"⚡ Đang dao động":"⚡ Oscillating",
"Đang phân tích trạng thái năng lượng của hệ...":"Analyzing the system energy state...",
"ℹ️ Chưa có cảnh báo năng lượng.":"ℹ️ No energy warnings.",
"Đang tính...":"Calculating...",
"CẢM BIẾN ĐỘNG LỰC HỌC CHI TIẾT":"DETAILED DYNAMICS SENSORS",
"⏱️ Trạng thái Cơ học":"⏱️ Mechanical State",
"Thời gian t =":"Time t =",
"Độ mòn khớp =":"Joint wear =",
"Lực dọc trục tại khớp 2 =":"Axial force at joint 2 =",
"Giới hạn chịu kéo =":"Tensile limit =",
"Tọa độ Khối tâm CM =":"Center of mass CM coordinates =",
"📐 Động học góc (Angular)":"📐 Angular Kinematics",
"📍 Tọa độ & Vận tốc Không gian":"📍 Spatial Coordinates & Velocity",
"⚖️ Lực & Mô-men (Forces & Torques)":"⚖️ Forces & Torques",
"Lực căng thanh T₁ =":"Rod tension T₁ =",
"Mô-men ma sát τ_f1 =":"Friction torque τ_f1 =",
"Công suất tiêu tán P_loss =":"Dissipated power P_loss =",
"⚡ Phân rã Năng lượng (Energy Breakdown)":"⚡ Energy Breakdown",
"Tổng Động năng K =":"Total kinetic energy K =",
"Tổng Thế năng U =":"Total potential energy U =",
"Cơ năng toàn phần E =":"Total mechanical energy E =",
"Năng lượng hiện có =":"Current energy =",
"Sai lệch cơ năng ΔE =":"Mechanical energy change ΔE =",
"Công lực ngoài W_ext =":"External work W_ext =",
"🌐 Môi trường & Động lượng":"🌐 Environment & Momentum",
"Mật độ không khí ρ =":"Air density ρ =",
"Động lượng tuyến tính |P| =":"Linear momentum |P| =",
"Mô-men động lượng |L| =":"Angular momentum |L| =",
"Người thực hiện":"Created by",
"năng lượng khả dụng":"available energy",
"còn ":"remaining ",
"Động năng hiện chỉ còn khoảng ":"Kinetic energy is currently about ",
"% ngân sách ban đầu. Các lần dao động sẽ có biên độ nhỏ hơn trước.":"% of the initial budget. Subsequent oscillations will have smaller amplitudes.",
"⚠️ Năng lượng hữu ích còn thấp; đây là dấu hiệu hệ đang tiến gần trạng thái nghỉ.":"⚠️ Usable energy is low; the system is approaching rest.",
"Động năng đang chiếm khoảng ":"Kinetic energy accounts for about ",
"% ngân sách năng lượng; các khối đang có tốc độ lớn.":"% of the energy budget; the masses are moving rapidly.",
"Năng lượng đang luân chuyển giữa K và U. Ma sát/cản làm cơ năng khả dụng giảm dần theo thời gian.":"Energy is cycling between K and U. Friction/drag gradually reduces available mechanical energy over time.",
" Tốc độ tiêu tán hiện tại khoảng ":" Current dissipation rate is about ",
" Hiện gần như không có công suất tiêu tán.":" There is currently almost no dissipated power.",
" • E đang giảm":" • E decreasing",
" • E đang tăng":" • E increasing",
"nhận diện liên tục":"continuous detection",
"cách ":"distance ",
"tiến ":"closing speed ",
"Rê chuột":"Hover",
"gần nhất:":"nearest:",
"khoảng cách":"distance",
"Đang chuyển động mạnh":"Strong motion"
});

Object.assign(tr,{
  "⚡ Đang dao động":"⚡ Oscillating",
  "Hệ đang trao đổi liên tục giữa động năng và thế năng.":"The system is continuously exchanging kinetic and potential energy.",
  "ℹ️ Năng lượng đang được theo dõi theo thời gian thực.":"ℹ️ Energy is being monitored in real time.",
  "Dao động rõ":"Clear oscillation",
  "⛔ Hệ thống đã dừng do quá tải":"⛔ System stopped due to overload",
  "K → U + hao hụt":"K → U + dissipation",
  "Rất yếu":"Very weak",
  "K ↔ U, biên độ giảm":"K ↔ U, decreasing amplitude",
  "Yếu":"Weak",
  "K trội → chuyển sang U":"K dominant → transferring to U",
  "Mạnh":"Strong",
  "K ${dE_info.K.toFixed(4)} J  |  U ${dE_info.U.toFixed(4)} J  |  E ${dE_info.E.toFixed(4)} J  |  năng lượng khả dụng ${remaining.toFixed(4)} J | còn ${remainPct.toFixed(2)}%":"K ${dE_info.K.toFixed(4)} J | U ${dE_info.U.toFixed(4)} J | E ${dE_info.E.toFixed(4)} J | available energy ${remaining.toFixed(4)} J | remaining ${remainPct.toFixed(2)}%",

  "🎯 Mục tiêu con trỏ":"🎯 Pointer target",
  "chưa khóa mục tiêu":"target not locked",
  "BẬT":"ON",
  "TẮT":"OFF",
  "khóa":"locked",
  "Khóa mục tiêu":"Lock target",
  "Khoảng cách":"Distance",
  "phương vị":"bearing",
  "TCA":"TCA",
  "Rê chuột | gần nhất:":"Hover | nearest:",
  "Khóa":"Lock",
  "BẬT":"ON",
  "TẮT":"OFF",
  "khóa":"locked",
  "chưa khóa mục tiêu":"target not locked",
  "nhận diện liên tục":"continuous detection",
  "gần nhất":"nearest",
  "phương vị":"bearing",
  "cách chuột":"mouse distance",
  "tiến":"closing speed",
  "Rê chuột":"Hover",
  "gần nhất:":"nearest:",
  "khoảng cách":"distance",
  "Đưa chuột tới vật thể để nhận diện; thông tin này không cần khóa mục tiêu.":"Move the pointer over an object to detect it; target locking is not required.",
  "Đã ngắt mô phỏng":"Simulation disconnected",
  "Tạm dừng":"Pause",
  "Tiếp tục":"Resume",
  "Không xác định":"Unknown",
  "Đã dừng":"Stopped",
  "phút":"minutes",
  "bước":"step",
  "Năng lượng đang luân chuyển giữa K và U. Ma sát/cản làm cơ năng khả dụng giảm dần theo thời gian.":"Energy is cycling between K and U. Friction/drag gradually reduces available mechanical energy over time.",
  "Tốc độ tiêu tán hiện tại khoảng":"Current dissipation rate is about",
  "Hiện gần như không có công suất tiêu tán.":"There is currently almost no dissipated power.",
  "E đang giảm":"E decreasing",
  "E đang tăng":"E increasing",
  "Mô phỏng đã chuyển sang trạng thái an toàn. Chuyển động của khối không còn được tính như con lắc liên kết.":"The simulation has entered a safe state. Mass motion is no longer calculated as a coupled pendulum.",
  "Cảnh báo: hệ đã vượt giới hạn cơ học. Hãy giảm lực, khối lượng, tốc độ hoặc tăng độ bền/giảm tác động.":"Warning: the system has exceeded the mechanical limit. Reduce force, mass, or speed, or increase strength/reduce loading.",
  "Hệ sắp dừng. Nếu ma sát/cản vẫn khác 0, biên độ sẽ tiếp tục giảm.":"The system is approaching rest. If friction/drag remains nonzero, the amplitude will continue to decrease.",
  "Các lần dao động sẽ có biên độ nhỏ hơn trước.":"Subsequent oscillations will have smaller amplitudes.",
  "Động năng đang chiếm khoảng":"Kinetic energy accounts for about",
  "của ngân sách năng lượng":"of the energy budget",
  "các khối đang có tốc độ lớn":"the masses are moving rapidly",
  "Năng lượng đang được theo dõi theo thời gian thực.":"Energy is being monitored in real time.",
  "Đang dao động ổn định":"Stable oscillation",
  "Đang chuyển động mạnh":"Strong motion"
});

Object.assign(tr,{
  "Con lắc kép — Phòng thí nghiệm động lực học nâng cao":"Double Pendulum — Advanced Dynamics Laboratory",
  "🎯 Theo dõi mục tiêu":"🎯 Target Tracking",
  "Chế độ":"Mode",
  "Tự thiết lập":"Auto setup",
  "Chọn mục tiêu":"Choose target",
  "Dự đoán tọa độ tương lai":"Future coordinate prediction",
  "🔮 Dự đoán tọa độ tương lai":"🔮 Future coordinate prediction",
  "Mục tiêu Aimbot":"Aimbot target",
  "Thời gian dự đoán (s)":"Prediction time (s)",
  "Số mốc dự đoán":"Prediction points",
  "Tọa độ hiện tại:":"Current coordinates:",
  "📍 Tọa độ dự đoán":"📍 Predicted coordinates",
  "t +":"t +",
  "X (m)":"X (m)",
  "Y (m)":"Y (m)",
  "Vx (m/s)":"Vx (m/s)",
  "Vy (m/s)":"Vy (m/s)",
  "Mục tiêu":"Target",
  "Giữa thanh 1":"Rod 1 midpoint",
  "Giữa thanh 2":"Rod 2 midpoint",
  "Đầu thanh 1":"Rod 1 end",
  "Đầu thanh 2":"Rod 2 end",
  "⚙️ Thiết lập mục tiêu":"⚙️ Set target",
  "Khóa mục tiêu":"Lock target",
  "Chưa thiết lập mục tiêu":"Target not configured",
  "👁️ Nhận diện rê chuột hoạt động độc lập: đưa chuột lên vật thể để xem thông tin thực tế, không cần khóa mục tiêu.":"👁️ Hover detection works independently: move the pointer over an object to view live information; target locking is not required.",
  "Di chuột lên mô hình":"Hover over the model",
  "Đưa chuột tới m₁, m₂ hoặc giữa thanh để xem chi tiết.":"Move the pointer to m₁, m₂, or a rod midpoint to view details.",
  "🎯 Mục tiêu con trỏ | chưa khóa mục tiêu":"🎯 Pointer target | target not locked",
  "Con lắc kép":"Double Pendulum",
  "Phòng thí nghiệm động lực học — mô hình cơ học Lagrange + RK4":"Dynamics laboratory — Lagrangian mechanics model + RK4",
  "🧪 Mô hình vật lý:":"🧪 Physical model:",
  "2 khâu cứng, khối điểm + thanh đồng chất, động lực học Lagrange, tích phân RK4, trọng lực, cản khí động theo vận tốc tương đối, ma sát nhớt/Coulomb, lực nổi và giá đỡ rung. Năng lượng được tính từ trạng thái tức thời.":"Two rigid links, point masses and uniform rods, Lagrangian dynamics, RK4 integration, gravity, aerodynamic drag based on relative velocity, viscous/Coulomb friction, buoyancy, and a vibrating support. Energy is computed from the instantaneous state.",
  "⚙️ Mở bảng Settings":"⚙️ Open Settings",
  "Âm thanh & Tính năng thực tế":"Sound & Real-time Features",
  "Âm thanh mô phỏng (Gió & Khớp ma sát)":"Simulation sound (Wind & Friction Joints)",
  "Chế độ độ mòn vô hạn (Không đứt, bỏ qua 100%)":"Infinite wear mode (Never breaks, bypasses 100%)",
  "Camera & Quan sát":"Camera & Observation",
  "Kéo trực tiếp m₁, m₂ để đổi vị trí/ném. Kéo nền để xoay góc nhìn. Cuộn chuột để zoom.":"Drag m₁ and m₂ directly to reposition/throw them. Drag the background to rotate the view. Scroll to zoom.",
  "Lưới tọa độ chuẩn":"Standard coordinate grid",
  "Vector vận tốc và gió":"Velocity and wind vectors",
  "Nhãn vật lý các điểm khối lượng":"Physical labels for mass points",
  "8 thông số khối lượng — chỉnh chính xác":"8 mass parameters — precise adjustment",
  "m₁ — vật 1":"m₁ — mass 1",
  "m₂ — vật 2":"m₂ — mass 2",
  "m₁ giữa — điểm giữa thanh 1":"m₁ midpoint — rod 1 midpoint",
  "m₂ giữa — điểm giữa thanh 2":"m₂ midpoint — rod 2 midpoint",
  "m₁ đầu — khối tập trung đầu thanh 1":"m₁ end — concentrated mass at rod 1 end",
  "m₂ đầu — khối tập trung đầu thanh 2":"m₂ end — concentrated mass at rod 2 end",
  "⚖️ Điều khiển khối lượng nâng cao":"⚖️ Advanced Mass Control",
  "Tổng khối lượng 5 vị trí":"Total mass for 5 positions",
  "Vị trí 1 — m₁":"Position 1 — m₁",
  "Vị trí 2 — m₂":"Position 2 — m₂",
  "Vị trí 3 — giữa thanh 1":"Position 3 — rod 1 midpoint",
  "Vị trí 4 — giữa thanh 2":"Position 4 — rod 2 midpoint",
  "Vị trí 5 — đầu thanh 1":"Position 5 — rod 1 end",
  "⚖️ Chia đều tổng khối lượng cho 5 vị trí":"⚖️ Distribute total mass across 5 positions",
  "✅ Áp dụng 5 giá trị vào mô hình":"✅ Apply 5 values to the model",
  "Ví dụ: nhập":"Example: enter",
  "rồi bấm “Chia đều” → mỗi vị trí":"then click “Distribute” → each position",
  ". Mỗi vị trí đều có thanh kéo riêng để chỉnh chính xác từng giá trị.":". Each position has its own slider for precise adjustment.",
  "Hình học & Cấu trúc":"Geometry & Structure",
  "Có thể chỉnh riêng chiều dài thanh 1 và thanh 2 để khảo sát ảnh hưởng của hình học đến chuyển động.":"Rod 1 and rod 2 lengths can be adjusted independently to study the effect of geometry on motion.",
  "Độ dài thanh 1 — L₁":"Rod 1 length — L₁",
  "Độ dài thanh 2 — L₂":"Rod 2 length — L₂",
  "Đường kính thanh d₁":"Rod diameter d₁",
  "Đường kính thanh d₂":"Rod diameter d₂",
  "Bán kính vật r₁":"Mass radius r₁",
  "Bán kính vật r₂":"Mass radius r₂",
  "Điều kiện ban đầu":"Initial Conditions",
  "Gia tốc trọng trường g":"Gravitational acceleration g",
  "Trái Đất":"Earth",
  "Mặt Trăng":"Moon",
  "Sao Hỏa":"Mars",
  "Mộc Tinh":"Jupiter",
  "Không trọng lực":"Zero gravity",
  "Vật liệu & Hao mòn ổ khớp":"Materials & Joint Wear",
  "Chất liệu cấu tạo (Chịu lực ly tâm)":"Material (Centrifugal Resistance)",
  "s1 - Vật liệu gốc (Tiêu chuẩn)":"s1 - Base Material (Standard)",
  "s2 - Thép (Cứng, chịu ly tâm tốt)":"s2 - Steel (Hard, high centrifugal resistance)",
  "s3 - Titanium (Rất cứng, siêu bền)":"s3 - Titanium (Very hard, ultra-durable)",
  "s4 - Sắt (Cứng trung bình)":"s4 - Iron (Medium hardness)",
  "s5 - Dây thừng (Mềm, mòn/đứt nhanh)":"s5 - Rope (Soft, wears/breaks quickly)",
  "Giới hạn đứt được ước tính từ ứng suất kéo cực hạn của vật liệu và tiết diện tròn của thanh/dây. Đây là mô hình giáo dục; giá trị thực tế còn phụ thuộc hình dạng, khuyết tật, mối nối và hệ số an toàn.":"The break limit is estimated from the material's ultimate tensile stress and the circular cross-section of the rod/rope. This is an educational model; real values also depend on geometry, defects, joints, and safety factors.",
  "Nhớt b₁":"Damping b₁",
  "Nhớt b₂":"Damping b₂",
  "Ma sát khô τ₁":"Dry friction τ₁",
  "Ma sát khô τ₂":"Dry friction τ₂",
  "Hệ số mòn cơ bản":"Base wear rate",
  "🔬 Chế độ nghiên cứu":"🔬 Research Mode",
  "Tốc độ mòn":"Wear speed",
  "x1 Chuẩn":"x1 Normal",
  "x10 Tối đa":"x10 Maximum",
  "Giới hạn giảm năng lượng":"Energy reduction limit",
  "🚀 Tối ưu hiệu năng CPU/GPU":"🚀 CPU/GPU Performance Optimization",
  "Đang phát hiện CPU/GPU...":"Detecting CPU/GPU...",
  "Mức giảm năng lượng mỗi giây":"Energy reduction per second",
  "Không khí & Gió động":"Air & Dynamic Wind",
  "Nhiệt độ":"Temperature",
  "Áp suất":"Pressure",
  "Gió tĩnh":"Static wind",
  "Hướng gió":"Wind direction",
  "Gió giật":"Wind gust",
  "Chu kỳ giật":"Gust period",
  "Cd vật":"Mass Cd",
  "Cản không khí":"Air resistance",
  "Bật gió":"Enable wind",
  "Độ nhớt μ":"Viscosity μ",
  "Mật độ chất lưu ρf":"Fluid density ρf",
  "Lực đẩy Archimedes":"Archimedes buoyancy force",
  "Môi trường nâng cao & Rung":"Advanced Environment & Vibration",
  "Hệ số ρ khí":"Air density factor",
  "Hệ số nhớt môi trường":"Environment viscosity factor",
  "Biên độ rung":"Vibration amplitude",
  "Tần số rung":"Vibration frequency",
  "Hướng rung":"Vibration direction",
  "Lực ngoại vi (Ném/Đẩy)":"External Force (Throw/Push)",
  "Lực F":"Force F",
  "Hướng lực":"Force direction",
  "Thời gian":"Duration",
  "Tác dụng lên m₁":"Apply to m₁",
  "Tác dụng lên m₂":"Apply to m₂",
  "Tác dụng lực":"Force target",
  "ĐIỀU KHIỂN MÔ PHỎNG":"SIMULATION CONTROL",
  "Tốc độ thời gian":"Time speed",
  "Vệt quỹ đạo":"Trajectory trail",
  "Tạm dừng":"Pause",
  "Reset hệ thống":"Reset system",
  "BẢNG ĐO LƯỜNG NĂNG LƯỢNG":"ENERGY MEASUREMENT PANEL",
  "Động năng (K)":"Kinetic energy (K)",
  "Thế năng (|U|)":"Potential energy (|U|)",
  "Tiêu hao (Loss)":"Dissipation (Loss)",
  "Cơ năng hiện có (E)":"Current mechanical energy (E)",
  "⚡ Đang dao động":"⚡ Oscillating",
  "Đang phân tích trạng thái năng lượng của hệ...":"Analyzing the system energy state...",
  "ℹ️ Chưa có cảnh báo năng lượng.":"ℹ️ No energy warnings.",
  "Chuyển hóa năng lượng":"Energy conversion",
  "Mức chuyển động":"Motion level",
  "Đang đánh giá":"Evaluating",
  "Tốc độ hao hụt":"Dissipation rate",
  "Ước tính còn dao động":"Estimated remaining oscillation",
  "Đang tính...":"Calculating...",
  "Năng lượng còn lại":"Remaining energy",
  "Ngân sách năng lượng":"Energy budget",
  "Tỷ lệ còn lại":"Remaining ratio",
  "Biến thiên E":"E change",
  "🔬 Phân rã động năng — kiểm tra chi tiết":"🔬 Kinetic energy decomposition — detailed check",
  "📐 Phân rã thế năng":"📐 Potential energy decomposition",
  "CẢM BIẾN ĐỘNG LỰC HỌC CHI TIẾT":"DETAILED DYNAMICS SENSOR",
  "⏱️ Trạng thái Cơ học":"⏱️ Mechanical State",
  "Thời gian t =":"Time t =",
  "Độ mòn khớp =":"Joint wear =",
  "Lực dọc trục tại khớp 2 =":"Axial force at joint 2 =",
  "Giới hạn chịu kéo =":"Tensile limit =",
  "Tọa độ Khối tâm CM = (":"Center of mass CM coordinates = (",
  "📐 Động học góc (Angular)":"📐 Angular Kinematics",
  "📍 Tọa độ & Vận tốc Không gian":"📍 Spatial Coordinates & Velocity",
  "⚖️ Lực & Mô-men (Forces & Torques)":"⚖️ Forces & Torques",
  "Lực căng thanh T₁ =":"Rod tension T₁ =",
  "Mô-men ma sát τ_f1 =":"Friction torque τ_f1 =",
  "Công suất tiêu tán P_loss =":"Dissipated power P_loss =",
  "⚡ Phân rã Năng lượng (Energy Breakdown)":"⚡ Energy Breakdown",
  "Tổng Động năng K =":"Total kinetic energy K =",
  "Tổng Thế năng U =":"Total potential energy U =",
  "Cơ năng toàn phần E =":"Total mechanical energy E =",
  "Năng lượng hiện có =":"Current energy =",
  "Sai lệch cơ năng ΔE =":"Mechanical energy change ΔE =",
  "Công lực ngoài W_ext =":"External work W_ext =",
  "🌐 Môi trường & Động lượng":"🌐 Environment & Momentum",
  "Mật độ không khí ρ =":"Air density ρ =",
  "Động lượng tuyến tính |P| =":"Linear momentum |P| =",
  "Mô-men động lượng |L| =":"Angular momentum |L| =",
  "👨‍💻 Người thực hiện: ATCX":"👨‍💻 Created by: ATCX"
});

function translateString(value){let out=String(value);const keys=Object.keys(tr).sort((a,b)=>b.length-a.length);for(const k of keys){if(k&&out.includes(k))out=out.split(k).join(tr[k]);}return tr[value]!==undefined?tr[value]:out;}

function translate(lang){
  lang=lang||"vi";
  currentLang=lang;
  document.documentElement.lang=lang;
  if(document.title){
    if(document.__atcxOriginalTitle===undefined)document.__atcxOriginalTitle=document.title;
    document.title=lang==="en"?translateString(document.__atcxOriginalTitle):document.__atcxOriginalTitle;
  }
  const nodes=[]; const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT); while(walker.nextNode())nodes.push(walker.currentNode);
  nodes.forEach(n=>{
    const current=n.nodeValue;
    if(n.__atcxOriginal===undefined)n.__atcxOriginal=current;
    const original=n.__atcxOriginal;
    const translated=translateString(original);
    if(lang==="en"){
      if(current!==translated && current!==original)n.__atcxOriginal=current;
      n.nodeValue=translateString(n.__atcxOriginal);
    }else{
      if(current!==original && current===translated)n.nodeValue=original;
      else if(current!==original)n.__atcxOriginal=current;
      n.nodeValue=n.__atcxOriginal;
    }
  });
  document.querySelectorAll("input[placeholder],[title],[aria-label]").forEach(el=>["placeholder","title","aria-label"].forEach(attr=>{if(!el.hasAttribute(attr))return;const k="__atcxOriginal_"+attr;if(el[k]===undefined)el[k]=el.getAttribute(attr);el.setAttribute(attr,lang==="en"?translateString(el[k]):el[k]);}));
  document.querySelectorAll("option").forEach(el=>{if(el.__atcxOriginal===undefined)el.__atcxOriginal=el.textContent;el.textContent=lang==="en"?translateString(el.__atcxOriginal):el.__atcxOriginal;});
  window.dispatchEvent(new CustomEvent("atcx-language-change",{detail:{lang}}));
}
let currentLang="vi",translateTimer=0,translating=false;
const observer=new MutationObserver(()=>{if(translating||currentLang!=="en")return;clearTimeout(translateTimer);translateTimer=setTimeout(()=>{translating=true;try{translate("en")}finally{translating=false}},20)});
function startTranslationObserver(){if(document.body)observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["placeholder","title","aria-label"]});}

function prefs(){return readCookie()}
function apply(v){
  v=v||prefs();
  document.documentElement.dataset.theme=v.theme||"dark";
  document.body.dataset.theme=v.theme||"dark";
  document.documentElement.lang=v.lang||"vi"; currentLang=v.lang||"vi";
  if(v.bg){
    const safe=String(v.bg).replace(/"/g,'\\"');
    document.documentElement.style.setProperty("--atcx-bg-image",'url("'+safe+'")');
    document.body.style.setProperty("--atcx-bg-image",'url("'+safe+'")');
    document.body.classList.add("atcx-custom-bg");
  }else{
    document.body.classList.remove("atcx-custom-bg");
    document.documentElement.style.removeProperty("--atcx-bg-image");
    document.body.style.removeProperty("--atcx-bg-image");
  }
  if(document.body){translate(v.lang||"vi");startTranslationObserver();}
}

function makeBanner(){
  if(hasConsent()||document.getElementById("atcx-cookie-banner"))return;
  const b=document.createElement("div");
  b.id="atcx-cookie-banner";
  b.innerHTML='<div><strong>🍪 Dữ liệu cookie</strong><p>Web chỉ dùng cookie để lưu <b>ngôn ngữ, giao diện sáng/tối và ảnh nền</b>. Bạn có thể xóa dữ liệu này bất cứ lúc nào trong Settings.</p><a class="atcx-cookie-more" href="cookie.html" data-page-transition>Xem thêm →</a></div><div class="atcx-cookie-actions"><button id="atcx-cookie-no">Không chấp nhận</button><button id="atcx-cookie-yes">Chấp nhận</button></div>';
  document.body.appendChild(b);
  b.querySelector("#atcx-cookie-yes").onclick=()=>{setConsent(true);saveCookie(readCookie());b.remove()};
  b.querySelector("#atcx-cookie-no").onclick=()=>{setConsent(false);delCookie();b.remove()};
  if((readCookie().lang||"vi")==="en")translate("en");
}

window.ATCXCookie={
  read:readCookie,save:saveCookie,delete:delCookie,apply,hasConsent,setConsent,
  ask:makeBanner,translate,t:(value)=>currentLang==="en"?translateString(value):String(value),
  lang:()=>currentLang
};
document.addEventListener("DOMContentLoaded",()=>{apply(readCookie());makeBanner()});
})();
